function items() {
  return [
    {
      id: 1,
      category: "Furniture",
      itemDesc: "Used Table",
      userName: "Milad",
      postCode: "M20 2WG",
      contactNumber: "073333220132",
      imgUrl: "./img/items-images/table.jpg",
    },
    {
      id: 2,
      category: "Furniture",
      itemDesc: "Kitchen Cabinet",
      userName: "Maziar",
      postCode: "M13 9GL",
      contactNumber: "0771976662",
      imgUrl: "./img/items-images/kitchen-cupboard.jpg",
    },
    {
      id: 3,
      category: "Electronics",
      itemDesc: "Old TV",
      userName: "Mohammed",
      postCode: "M14 9PW",
      contactNumber: "0700129345",
      imgUrl: "./img/items-images/old-tv.jpg",
    },
    {
      id: 4,
      category: "Clothes",
      itemDesc: "Women Blazer",
      userName: "Milad",
      postCode: "M20 2WG",
      contactNumber: "073333220132",
      imgUrl: "./img/items-images/dress.jpg",
    },
    {
      id: 5,
      category: "Electronics",
      itemDesc: "Apple Laptop",
      userName: "Maziar",
      postCode: "M13 9GL",
      contactNumber: "0771976662",
      imgUrl: "./img/items-images/laptop.jpg",
    },
    {
      id: 6,
      category: "Electronics",
      itemDesc: "Samsung S2",
      userName: "Mohammed",
      postCode: "M14 9PW",
      contactNumber: "0700129345",
      imgUrl: "./img/items-images/mobile.jpg",
    },
    {
      id: 7,
      category: "Furniture",
      itemDesc: "Used 3 Seaters Sofa",
      userName: "Milad",
      postCode: "M20 2WG",
      contactNumber: "073333220132",
      imgUrl: "./img/items-images/sofa.jpg",
    },
    {
      id: 8,
      category: "Electronics",
      itemDesc: "Apple Air Pods",
      userName: "Maziar",
      postCode: "M13 9GL",
      contactNumber: "0771976662",
      imgUrl: "./img/items-images/airpods.jpg",
    },
    {
      id: 9,
      category: "Games & Toys",
      itemDesc: "Used Xbox",
      userName: "Mohammed",
      postCode: "M14 9PW",
      contactNumber: "0700129345",
      imgUrl: "./img/items-images/xbox.jpg",
    },
    {
      id: 10,
      category: "Games & Toys",
      itemDesc: "Used Xbox controller",
      userName: "Milad",
      postCode: "M20 2WG",
      contactNumber: "073333220132",
      imgUrl: "./img/items-images/xbox-controller.jpg",
    },
  ];
}
