function items() {
  return [
    {
      id: 1,
      category: "Furniture",
      itemDesc: "Used Table",
      userName: "Milad",
      postCode: "M20 2WG",
      contactNumber: "073333220132",
      imgUrl: "https://i.imgur.com/6QCf2R2.jpg",
    },
    {
      id: 2,
      category: "Furniture",
      itemDesc: "Kitchen Cabinet",
      userName: "Maziar",
      postCode: "M13 9GL",
      contactNumber: "0771976662",
      imgUrl: "https://i.imgur.com/78VwBvM.jpg",
    },
    {
      id: 3,
      category: "Electronics",
      itemDesc: "Old TV",
      userName: "Mohammed",
      postCode: "M14 9PW",
      contactNumber: "0700129345",
      imgUrl: "https://i.imgur.com/iv8pkD8.jpg",
    },
    {
      id: 4,
      category: "Clothes",
      itemDesc: "Women Blazer",
      userName: "Milad",
      postCode: "M20 2WG",
      contactNumber: "073333220132",
      imgUrl: "https://i.imgur.com/0VEegNU.jpg",
    },
    {
      id: 5,
      category: "Electronics",
      itemDesc: "Apple Laptop",
      userName: "Maziar",
      postCode: "M13 9GL",
      contactNumber: "0771976662",
      imgUrl: "https://i.imgur.com/zRSg5uA.jpg",
    },
    {
      id: 6,
      category: "Electronics",
      itemDesc: "Samsung S2",
      userName: "Mohammed",
      postCode: "M14 9PW",
      contactNumber: "0700129345",
      imgUrl: "https://i.imgur.com/vQTY3Pl.jpg",
    },
    {
      id: 7,
      category: "Furniture",
      itemDesc: "Used 3 Seaters Sofa",
      userName: "Milad",
      postCode: "M20 2WG",
      contactNumber: "073333220132",
      imgUrl: "https://i.imgur.com/2NRygpJ.jpg",
    },
    {
      id: 8,
      category: "Electronics",
      itemDesc: "Apple Air Pods",
      userName: "Maziar",
      postCode: "M13 9GL",
      contactNumber: "0771976662",
      imgUrl: "https://i.imgur.com/Q1FIW9F.jpg",
    },
    {
      id: 9,
      category: "Games & Toys",
      itemDesc: "Used Xbox",
      userName: "Mohammed",
      postCode: "M14 9PW",
      contactNumber: "0700129345",
      imgUrl: "https://i.imgur.com/UudH2Ai.jpg",
    },
    {
      id: 10,
      category: "Games & Toys",
      itemDesc: "Used Xbox controller",
      userName: "Milad",
      postCode: "M20 2WG",
      contactNumber: "073333220132",
      imgUrl: "https://i.imgur.com/VL1ZOO3.jpg",
    },
  ];
}
